#!/usr/bin/env python

import os
import json

allSettings = []
allInitContent = []

for dirName, subdirList, fileList in os.walk('./src/common/res/features/'):

    if ('settings.json' in fileList):
        with open(os.path.join(dirName, 'settings.json'), 'r') as settingsFile:
            settingsContents = json.loads(settingsFile.read())

            if (isinstance(settingsContents, dict)):
                allSettings.append(settingsContents)
            else:
                for setting in settingsContents:
                    allSettings.append(setting)

    if ('init.js' in fileList):
        with open(os.path.join(dirName, 'init.js'), 'r') as initFile:
            allInitContent.append(initFile.read())


# Write the settings file:
# Note, yes it's a JSON file and they're not supposed to have comments by default.
# This one is really useful to us, so we're going to run it through JSON.minify
# before we read it. See the note from JSON creator here:
# https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr
with open('./src/common/res/features/allSettings.js', 'w') as settingsFile:
    settingsFile.write(('/**********************************************************\n'
                        '* Warning: This is a file generated by the build process. *\n'
                        '*                                                         *\n'
                        '* Any changes you make manually will be overwritten       *\n'
                        '* the next time you run ./build or build.bat!             *\n'
                        '**********************************************************/\n\n'))
    settingsFile.write('var toolkitForYnabSettings = ' + json.dumps(allSettings))


# Write the init file:
with open('./src/common/res/features/allInits.js', 'w') as allInits:
    allInits.write(('/**********************************************************\n'
                    '* Warning: This is a file generated by the build process. *\n'
                    '*                                                         *\n'
                    '* Any changes you make manually will be overwritten       *\n'
                    '* the next time you run ./build or build.bat!             *\n'
                    '**********************************************************/\n\n'))
    allInits.write('\n'.join(allInitContent))

print('[   INFO] All inits and settings written correctly')
