#!/usr/bin/env bash

if [ "$1" == "" ]; then
  echo "Please supply a Crowdin API key, obtained on this page: http://translate.toolkitforynab.com/project/toolkit-for-ynab/settings#api"
  exit 1
fi

cd source/common/res/features/l10n/

echo "Loading actual localisation strings from app.youneedabudget.com."
phantomjs get_ember_strings.js > actual.json

echo "Merging actual localisation into current one."
jq -s '.[0] * .[1]' en.json actual.json > new.json
mv new.json en.json

echo "Sending updated localisation to Crowdin."
curl \
  -F "files[en.json]=@en.json" \
  https://api.crowdin.com/api/project/toolkit-for-ynab/update-file\?key\=$1

cd -
