/* eslint-disable */
/*
 ***********************************************************
 * Warning: This is a file generated by the build process. *
 *                                                         *
 * Any changes you make manually will be overwritten       *
 * the next time you run ./build or build.bat!             *
 ***********************************************************
 */

if (typeof window.ynabToolKit === 'undefined') {
  window.ynabToolKit = {};
}

export const settingMigrationMap = {
  CategorySoloMode: {
    oldSettingName: 'ToggleMasterCategories',
    settingMapping: { true: 'cat-toggle-all' },
  },
  AutoEnableRunningBalance: {
    oldSettingName: 'RunningBalance',
    settingMapping: { '0': false, '1': true, '2': true },
  },
};
export const allToolkitSettings = [
  {
    name: 'l10n',
    title: 'Localization of YNAB',
    default: '0',
    section: 'general',
    type: 'select',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Czech (39%)', value: 'czech' },
      { name: 'Tagalog (1%)', value: 'tagalog' },
      { name: 'Catalan (1%)', value: 'catalan' },
      { name: 'Portuguese, Brazilian (65%)', value: 'portuguese, brazilian' },
      { name: 'Chinese Simplified (3%)', value: 'chinese simplified' },
      { name: 'Russian (53%)', value: 'russian' },
      { name: 'Finnish (24%)', value: 'finnish' },
      { name: 'Icelandic (4%)', value: 'icelandic' },
      { name: 'Spanish (45%)', value: 'spanish' },
      { name: 'Vietnamese (5%)', value: 'vietnamese' },
      { name: 'Hungarian (25%)', value: 'hungarian' },
      { name: 'Turkish (38%)', value: 'turkish' },
      { name: 'Swedish (22%)', value: 'swedish' },
      { name: 'Japanese (1%)', value: 'japanese' },
      { name: 'German (49%)', value: 'german' },
      { name: 'Latvian (8%)', value: 'latvian' },
      { name: 'Ukrainian (2%)', value: 'ukrainian' },
      { name: 'Italian (8%)', value: 'italian' },
      { name: 'Chinese Traditional (23%)', value: 'chinese traditional' },
      { name: 'Danish (21%)', value: 'danish' },
      { name: 'Polish (78%)', value: 'polish' },
      { name: 'Serbian (Cyrillic) (58%)', value: 'serbian (cyrillic)' },
      { name: 'French (43%)', value: 'french' },
      { name: 'Norwegian (31%)', value: 'norwegian' },
      { name: 'Romanian (1%)', value: 'romanian' },
      { name: 'Portuguese (17%)', value: 'portuguese' },
      { name: 'Indonesian (38%)', value: 'indonesian' },
      { name: 'Slovenian (1%)', value: 'slovenian' },
      { name: 'Arabic (12%)', value: 'arabic' },
      { name: 'Lithuanian (1%)', value: 'lithuanian' },
      { name: 'Dutch (40%)', value: 'dutch' },
    ],
    actions: {
      '0': ['injectScript', 'legacy\\features\\l10n\\default.js'],
      portuguese: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Portuguese.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      czech: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Czech.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      japanese: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Japanese.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      spanish: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Spanish.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      polish: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Polish.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      arabic: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Arabic.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      swedish: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Swedish.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      icelandic: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Icelandic.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      vietnamese: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Vietnamese.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      romanian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Romanian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      slovenian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Slovenian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      dutch: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Dutch.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      'portuguese, brazilian': [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Portuguese, Brazilian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      'serbian (cyrillic)': [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Serbian (Cyrillic).js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      danish: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Danish.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      indonesian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Indonesian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      tagalog: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Tagalog.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      hungarian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Hungarian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      ukrainian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Ukrainian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      lithuanian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Lithuanian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      french: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\French.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      catalan: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Catalan.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      german: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\German.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      russian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Russian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      finnish: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Finnish.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      norwegian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Norwegian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      'chinese traditional': [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Chinese Traditional.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      turkish: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Turkish.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      'chinese simplified': [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Chinese Simplified.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      latvian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Latvian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
      italian: [
        'injectScript',
        'legacy\\features\\l10n\\locales\\Italian.js',
        'injectScript',
        'legacy\\features\\l10n\\main.js',
      ],
    },
    description: 'Localization of interface.',
  },
  {
    name: 'AssistedClear',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Assisted Clear',
    description:
      'This feature assists you in the reconcilation process by locating uncleared transactions that should be cleared based on the desired reconcile amount.',
  },
  {
    name: 'AutoDistributeSplits',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Add Auto-Distribute Button To Split Transactions',
    description:
      'Allows you to distribute the remaining amount in a split transaction proportionally to sub-transactions',
  },
  {
    name: 'AutoEnableRunningBalance',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Automatically Enable Running Balance',
    description: 'Enables YNAB\'s native "Running Balance" by default for each account register.',
  },
  {
    name: 'AutomaticallyMarkAsCleared',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Automatically Mark Transaction as Cleared',
    description: 'Automatically mark transaction as cleared when you enter it manually.',
  },
  {
    name: 'BottomNotificationBar',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Bottom Notification Bar',
    description:
      'Move the notification bar to the bottom as an overlay. This prevents the transactions from "jumping around."',
  },
  {
    name: 'BulkEditMemo',
    type: 'checkbox',
    default: true,
    section: 'accounts',
    title: 'Bulk Edit Memo',
    description: 'Adds option to edit memo on transactions to the edit menu.',
  },
  {
    name: 'BulkManagePayees',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Bulk Manage Payees',
    description:
      'Adds an option to the transaction edit drop-down menu to manage payees for the current selection.',
  },
  {
    name: 'CalculateIRR',
    type: 'select',
    default: 'disabled',
    section: 'accounts',
    title: 'Calculate Internal Rate of Return',
    description:
      'Calculate Internal Rate of Return for Tracking Accounts. Set Tracking Account contributions to this color to calculate IRR',
    options: [
      { name: 'disabled', value: null },
      { name: 'Red', value: 'Red' },
      { name: 'Orange', value: 'Orange' },
      { name: 'Yellow (Default)', value: 'Yellow' },
      { name: 'Green', value: 'Green' },
      { name: 'Blue', value: 'Blue' },
      { name: 'Purple', value: 'Purple' },
    ],
  },
  {
    name: 'CalendarFirstDay',
    type: 'select',
    default: '0',
    section: 'accounts',
    title: 'First Day of the Week in Calendar',
    description: 'Change the first day of the week when viewing the calendar.',
    options: [
      { name: 'Default (Sunday)', value: '0' },
      { name: 'Monday', value: '1' },
      { name: 'Tuesday', value: '2' },
      { name: 'Wednesday', value: '3' },
      { name: 'Thursday', value: '4' },
      { name: 'Friday', value: '5' },
      { name: 'Saturday', value: '6' },
    ],
  },
  {
    name: 'ChangeEnterBehavior',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Change Behaviour of Enter Key When Adding Transactions',
    description:
      "When you press enter while adding transactions, the default behaviour is 'Save and add another'. This option changes it to just 'Save'.",
  },
  {
    name: 'ChangeMemoEnterBehavior',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Change Behaviour of Enter Key on the Memo field When Adding or Editing Transactions',
    description:
      "When you press enter on the memo field while adding or editing a transaction, the default behaviour is 'Save' or 'Save and add another'. This option changes it to move to the next field.",
  },
  {
    name: 'CheckNumbers',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Add Check Number Column',
    description: 'Adds the check number column to your account view.',
  },
  {
    name: 'ClearSelection',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Clear Selection',
    description:
      'Adds an option to the transaction edit drop-down menu to clear the current selection.',
  },
  {
    name: 'ConfirmKeyboardCancelationOfTransactionChanges',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Confirm keyboard-initiated transaction cancelation',
    description:
      'Displays a pop-up confirmation prompt when transaction row\'s "Cancel" action is triggered by keyboard press ("Enter"). This guards against inadvertent discarding of complex split transaction entries in keyboard driven entry workflows.',
  },
  {
    name: 'CtrlEnterCleared',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Clear new transactions with CTRL+Enter',
    description: 'Automatically clear a new transaction by pressing CTRL+Enter (CMD on Mac).',
  },
  {
    name: 'CustomFlagNames',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Set Custom Flag Names (with Tooltips)',
    description:
      'Adds the ability to set custom flag names. Tooltip for the flag name will only be visible when the cursor is hovered over the flag. *__Note__: Custom flag names are stored locally in the browser in which they are set and will __not__ be carried over to other browsers/computers. Custom flag names will be lost if browser data is cleared.*',
  },
  {
    name: 'DeselectTransactionsOnSave',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Deselect Transactions on Save',
    description: 'Deselects all transactions after any transaction is saved.',
  },
  {
    name: 'EasyTransactionApproval',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Easy Transaction Approval',
    description:
      "Quickly approve scheduled or linked transactions by selecting the transaction(s) and pressing 'a' or 'enter' on your keyboard. Alternately, approve single scheduled or linked transactions by right clicking on the blue 'i' or link icon.",
  },
  {
    name: 'AccountsEmphasizedInflows',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Emphasize Inflows',
    description: 'Make values in the inflow column green.',
  },
  {
    name: 'AccountsEmphasizedOutflows',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Emphasize Outflows',
    description: 'Make values in the outflow column red and put them in parenthesis.',
  },
  {
    name: 'LargerClickableIcons',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Larger Clickable Area for Icons',
    description: 'Makes the uncleared, cleared and reconciled icons easier to select.',
  },
  {
    name: 'LastReconciledDate',
    type: 'select',
    default: 'disabled',
    section: 'accounts',
    title: 'Show Last Reconciliation Details',
    description:
      'Show the last reconciled date and or days since last reconciled of the current account in the header',
    options: [
      { name: 'Disabled', value: 'disabled' },
      { name: 'Date Last Reconciled', value: 'last-date' },
      { name: 'Days Since Reconciled', value: 'days-since' },
      { name: 'Both', value: 'last-date-days-since' },
    ],
  },
  {
    name: 'MemoAsMarkdown',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Allow Markdown in Memo',
    description:
      'Adds Markdown parsing to memos, allowing support for links and other formatting tools. Learn how to use Markdown [here](https://www.markdownguide.org/cheat-sheet).',
  },
  {
    name: 'ReconcileBalance',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Show Reconciled Balance',
    description:
      'Show the current reconciled balance excluding cleared and non-reconciled transactions',
  },
  {
    name: 'ReconcileConfetti',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Show Reconcile Confetti',
    description:
      'When an account is successfully reconciled, show a fun confetti animation to mark your tremendous achievement.',
  },
  {
    name: 'ReconciledTextColor',
    type: 'select',
    default: false,
    section: 'accounts',
    title: 'Reconciled Text Colour',
    description:
      'Makes the text on reconciled transactions appear in a more obvious colour of your choosing.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Green', value: '1' },
      { name: 'Light gray', value: '2' },
      { name: 'Dark gray', value: '3' },
      { name: 'Dark gray with green background', value: '4' },
    ],
  },
  {
    name: 'RightClickToEdit',
    type: 'checkbox',
    default: true,
    section: 'accounts',
    title: 'Show Menu When Right Clicking On Transaction',
    description:
      'Right clicking on a transaction will show the contextual menu, allowing easy access to the Edit menu options.',
  },
  {
    name: 'RowHeight',
    type: 'select',
    default: '0',
    section: 'accounts',
    title: 'Height of Rows in Account Register',
    description:
      'Change the height of transaction rows so more of them are displayed on the screen.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Compact', value: '1' },
      { name: 'Slim', value: '2' },
    ],
  },
  {
    name: 'SetMultipleFlags',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Edit Multiple Flags at Once',
    description:
      'Adds a button to the edit dialog which allows you to set the flag. If multiple transactions are selected, all transactions are updated.',
  },
  {
    name: 'ShowCategoryBalance',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Show Available Category Balance on Hover',
    description:
      'Adds the total available balance to the category tooltip on each row in the Accounts register.',
  },
  {
    name: 'SpareChange',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Show Spare Change',
    description:
      'Imagine if you paid for all purchases in whole dollars. Shows a total of the spare change you would accumulate for the selected outflow transactions.',
  },
  {
    name: 'SplitTransactionAutoAdjust',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Auto Adjust Split Transactions',
    description:
      'When entering split transactions, each additional split will be auto-filled with the current remaining amount.',
  },
  {
    name: 'AccountsStripedRows',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Striped Transaction Rows',
    description:
      'Shows a different-color background on every other transaction row. See the Color for Striped Transaction Rows settings to specify the color to be used.',
  },
  {
    name: 'AccountsStripedRowsColor',
    type: 'color',
    default: '#fafafa',
    section: 'accounts',
    title: 'Color for Striped Transaction Rows',
    description:
      'When the Striped Transaction Rows feature is enabled, alternating rows use this color as the background. The default is #fafafa.',
  },
  {
    name: 'AccountsStripedRowsDarkColor',
    type: 'color',
    default: '#1e1e1f',
    section: 'accounts',
    title: 'Color for Striped Transaction Rows - Dark Theme',
    description:
      'When the Striped Transaction Rows feature is enabled, in dark theme, alternating rows use this color as the background. The default is #1e1e1f.',
  },
  {
    name: 'SwapClearedFlagged',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Swap cleared and flagged columns',
    description:
      'Place the Cleared column on the left and the Flagged column on the right sides of an account screen.',
  },
  {
    name: 'ToggleAccountColumns',
    type: 'checkbox',
    default: true,
    section: 'accounts',
    title: 'Toggle Memo Column',
    description:
      'Adds option to toggle the memo column as visible or not to the account register "View" menu',
  },
  {
    name: 'ToggleSplits',
    type: 'checkbox',
    default: false,
    section: 'accounts',
    title: 'Add a Toggle Splits Button to the Account(s) toolbar',
    description:
      'Clicking the Toggle Splits button shows or hides all sub-transactions within all split transactions.',
  },
  {
    name: 'ToggleTransactionFilters',
    type: 'select',
    default: '0',
    section: 'accounts',
    title: 'Toggle Scheduled and Reconciled Transaction Buttons',
    description: 'Easily show and hide scheduled and reconciled transactions with one click.',
    options: [
      { name: 'Disabled', value: '0' },
      { name: 'Show Icons', value: '1' },
      { name: 'Show Icons and Text Labels', value: '2' },
    ],
  },
  {
    name: 'DisableToolkit',
    type: 'checkbox',
    default: false,
    section: 'advanced',
    title: 'Disable Toolkit for YNAB',
    description: 'Turn all features on and off with a single switch.',
  },
  {
    name: 'DisplayTargetGoalAmount',
    type: 'select',
    default: '0',
    section: 'budget',
    title: 'Display Target Goal Amount And Overbudget Warning',
    description:
      "Adds a 'Goal' column which displays the target goal amount for every category with a goal, and a warning in red if you have budgeted beyond your goal.",
    options: [
      { name: 'Do not display goal amount (default)', value: '0' },
      { name: 'Display goal amount and warn of overbudget with red', value: '1' },
      { name: 'Display goal amount but show overbudget as green', value: '2' },
      { name: 'Display goal amount with no emphasis', value: '3' },
    ],
  },
  {
    name: 'GoalIndicator',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Add Goals Indication',
    description:
      'Add indicators for subcategories with goals. Types: (M)onthly goal,  target by (D)ate goal, (T)arget without date, and (U)pcoming transactions.',
  },
  {
    name: 'GoalWarningColor',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Goal Indicator Warning Color',
    description:
      'Change the orange goal underfunded warning to blue, to better differentiate it from credit card overspending.',
  },
  {
    name: 'HighlightNegatives',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Highlight all Negative Category Balances Red',
    description:
      'Ensure all negative balances are highlighted red instead of yellow, even with credit card spending.',
  },
  { name: 'BudgetCategoryFeatures', section: 'system', default: true },
  {
    name: 'TargetBalanceWarning',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Warn When Target Balance is Not Reached',
    description:
      'Will highlight balances of categories with Target Balances that have not yet been met.',
  },
  {
    name: 'BudgetProgressBars',
    type: 'select',
    default: false,
    hidden: false,
    section: 'budget',
    title: 'Budget Rows Progress Bars',
    description:
      'Add progress bars and a vertical bar that shows how far you are through the month to category rows.',
    options: [
      { name: 'Off', value: '0' },
      { name: 'Goals progress', value: 'goals' },
      { name: 'Pacing progress', value: 'pacing' },
      { name: 'Pacing on name column and goals on budgeted column', value: 'both' },
    ],
  },
  {
    name: 'BudgetSpendingGoal',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Spending Goal',
    description:
      'Allows the monthly funding goal to be set as a max spending goal for each category.',
  },
  {
    name: 'CategoryActivityPopupWidth',
    type: 'select',
    default: '0',
    section: 'budget',
    title: 'Width of Category Popup',
    description:
      'Makes the screen that pops up when you click on activity from a budget category wider so you can see more details of the transactions listed.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Medium', value: '1' },
      { name: 'Large', value: '2' },
    ],
  },
  {
    name: 'CategorySoloMode',
    type: 'select',
    default: false,
    section: 'budget',
    title: 'Toggle Master Categories',
    description:
      'Adds ability to toggle all master categories at once. Alternatively, "Solo Mode" can be used to toggle all but a single category at once.',
    options: [
      { name: 'Off', value: '0' },
      { name: 'Enable Category Solo Mode', value: 'cat-solo-mode' },
      { name: 'Enable Toggle All Categories', value: 'cat-toggle-all' },
      { name: 'Enable both', value: 'cat-solo-mode-toggle-all' },
    ],
  },
  {
    name: 'CheckCreditBalances',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Paid in Full Credit Card Assist',
    description:
      'Highlights credit card category balances with a yellow warning if the balance of the category does not match the account balance. Adds a button to the Inspector to rectify the difference.',
  },
  {
    name: 'MasterCategoryRowColor',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Colored Master Category Row',
    description: 'Adds Color to Master Category Row.',
  },
  {
    name: 'CreditCardEmoji',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Credit Card Emoji',
    description: 'Adds a credit card emoji 💳 to the "Credit Card Payments" category.',
  },
  {
    name: 'DateOfMoney',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Date Of Money',
    description:
      'Hover the mouse over Age of Money to display the date of the income.\n For example, on 11th January with Age of Money = 10, Date of Money would be 1st January.',
  },
  {
    name: 'DaysOfBuffering',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Days of Buffering Metric',
    description:
      "This calculation shows how long your money would likely last if you never earned another cent based on your average spending. We know that no month is 'average' but this should give you some idea of how much of a buffer you have. Equal to budget accounts total divided by the average daily outflow. That comes from sum of all outflow transactions from on budget accounts only divided by the age of budget in days. You can also change the number of days taken into account by this metric with the 'Days of Buffering History Lookup' setting.",
  },
  {
    name: 'DaysOfBufferingHistoryLookup',
    type: 'select',
    default: '0',
    section: 'budget',
    title: 'Days of Buffering History Lookup',
    description: 'How old transactions should be used for average daily outflow calculation.',
    options: [
      { name: 'All', value: '0' },
      { name: '1 year', value: '12' },
      { name: '6 months', value: '6' },
      { name: '3 months', value: '3' },
      { name: '1 month', value: '1' },
    ],
  },
  {
    name: 'DaysOfBufferingDate',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Days Of Buffering Metric - Date',
    description:
      'Hover the mouse over Days of Buffering to display the equivalent Date for Days of Buffering.\n For example, on 1st January with Days of Buffering = 10, Date of Buffering would be 11th January.',
  },
  {
    name: 'DisplayTotalMonthlyGoals',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Display Total Monthly Goals',
    description:
      "Adds a 'Total Monthly Goals' to the budget inspector, which displays the total amount of monthly funding goals.",
  },
  {
    name: 'DisplayUpcomingAmount',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Show Upcoming Transaction Total',
    description: 'Adds the total of upcoming transactions alongside activity for each category.',
  },
  {
    name: 'EnlargeCategoriesDropdown',
    type: 'checkbox',
    default: true,
    section: 'budget',
    title: 'Make the Categories Dropdown Larger',
    description:
      'The Categories Dropdown that shows in the move money modal is quite small. Show more categories if the page real estate allows for it.',
  },
  {
    name: 'FilterCategories',
    type: 'checkbox',
    default: true,
    section: 'budget',
    title: 'Enable Categories Filter',
    description: 'Enable textbox at budget page for categories filtering',
  },
  {
    name: 'HideAgeOfMoney',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Hide Age of Money Calculation',
    description:
      "Hides the Age of Money calculation. Some users find it's not relevant or helpful for them, so they'd rather hide it. NOTE: YNAB will continue to run its Age of Money calculations, so the data will be up to date if you decide to show it again.",
  },
  {
    name: 'HideTotalAvailable',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Hide Total Available',
    description: 'Hides the "Total Available" section in the budget inspector.',
  },
  {
    name: 'HoveredBudgetRows',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Highlight Budget Rows On Hover',
    description: 'Shows a light gray background on category rows when hovered over.',
  },
  {
    name: 'CurrentMonthIndicator',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Current Month Indicator',
    description:
      "Changes the header bar's background color to a lighter blue when viewing the current month to better differentiate between months.",
  },
  {
    name: 'IncomeFromLastMonth',
    type: 'select',
    default: '0',
    section: 'budget',
    title: 'Income From Last Month',
    description: 'Show total of incoming transactions for last month in the header.',
    options: [
      { name: 'Disabled', value: '0' },
      { name: 'Use previous month', value: '1' },
      { name: 'Use month before last', value: '2' },
      { name: 'Use two months before last', value: '3' },
      { name: 'Use three months before last', value: '4' },
    ],
  },
  {
    name: 'LinkToInflows',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Link to Inflows',
    description:
      'Clicking on the "Total Inflows" section of the budget inspector will link to the inflow transactions for that month.',
  },
  {
    name: 'MonthlyNotesPopupWidth',
    type: 'select',
    default: '0',
    section: 'budget',
    title: 'Width of Monthly Notes Popup',
    description:
      "Makes the screen that pops up when you click on 'Enter a note...' below the month name wider so you can add more text.",
    options: [
      { name: 'Default', value: '0' },
      { name: 'Medium', value: '1' },
      { name: 'Large', value: '2' },
    ],
  },
  {
    name: 'NotesAsMarkdown',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Allow Markdown in Notes',
    description:
      'Adds Markdown parsing to notes, allowing support for links, bullet points, and other formatting tools. Learn how to use Markdown [here](https://www.markdownguide.org/cheat-sheet).',
  },
  {
    name: 'Pacing',
    type: 'select',
    default: false,
    section: 'budget',
    title: 'Add Pacing to the Budget',
    description:
      "Add a column for 'pacing' which shows you how much money you've spent based on how far you are through the month. Note that clicking on the pacing value will toggle emphasis, allowing you to selectively enable the feature per category.",
    options: [
      { name: 'Disabled', value: '0' },
      { name: 'Show Full Amount', value: '1' },
      { name: 'Show Simple Indicator', value: '2' },
      { name: 'Show Days Ahead/Behind Schedule', value: '3' },
    ],
  },
  {
    name: 'QuickBudgetWarning',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Warn When Clicking a Quick Budget Option',
    description:
      'When this feature is activated, there will be a warning if you have already budgeted something.',
  },
  {
    name: 'RemovePositiveHighlight',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Unhighlight all Positive Category Balances',
    description:
      'Removes the highlight colour from positive (or zero) category balances and colours positive balances green instead.',
  },
  {
    name: 'RemoveZeroCategories',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Remove Zero and Negative Categories When Covering Over-Budgeting',
    description:
      "\nDefault YNAB behaviour is to show these categories when covering overbudgeting, but since they've got no money in them they won't help you. Let's clean up the menu.\n",
  },
  {
    name: 'RowsHeight',
    type: 'select',
    default: '0',
    section: 'budget',
    title: 'Height of Budget Rows',
    description:
      'Makes the budget rows skinnier than the default YNAB style so that you can fit more on the screen.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Compact', value: '1' },
      { name: 'Slim', value: '2' },
      { name: 'Slim with smaller font', value: '3' },
    ],
  },
  {
    name: 'SeamlessBudgetHeader',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Seamless Budget Header',
    description:
      'Remove the borders between selected month, funds and Age of Money in the budget header.',
  },
  {
    name: 'StealingFromFuture',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Stealing From Future Alert',
    description:
      'Highlights "Budget Next Month" red when you\'ve gone negative as some point in the future.',
  },
  {
    name: 'StripedBudgetRows',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'Striped Budget Rows',
    description: 'Shows a light gray background on alternating category rows.',
  },
  {
    name: 'ToBeBudgetedWarning',
    type: 'checkbox',
    default: false,
    section: 'budget',
    title: 'To Be Budgeted Warning',
    description:
      "Changes the 'To Be Budgeted' background color to yellow if there is unallocated money left to be budgeted.",
  },
  {
    name: 'AccountsDisplayDensity',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Account Name Height',
    description:
      'Makes the account names smaller so that you can see more of the account names and fit more on the screen.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Compact', value: '1' },
      { name: 'Slim', value: '2' },
    ],
  },
  {
    name: 'BetterScrollbars',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Better scrollbars',
    description: 'Provides smaller and cleaner scrollbars across the application.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Small', value: '1' },
      { name: 'Tiny', value: '2' },
      { name: 'Off', value: '3' },
    ],
  },
  {
    name: 'BudgetQuickSwitch',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Budget Quick Switch',
    description:
      "Adds the list of budgets to the Open Budget dropdown so you don't have to navigate to the 'Open Budget' page to switch budgets.",
  },
  {
    name: 'CategoryActivityCopy',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Add Copy Transactions to Activity Modals',
    description:
      'Adds a button to copy transactions displayed in the various Activity Modals (Budget and Reports pages).',
  },
  {
    name: 'ColourBlindMode',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Colour Blind Mode',
    description:
      'Changes colours like red, yellow and green in the interface to colours and shapes that are more easily distinguishable by colourblind people.',
  },
  {
    name: 'EditAccountButton',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Hide Edit Account Button',
    description:
      'Allows you to hide the edit account button to help prevent accidentally clicking on it.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Hidden (right-click to edit)', value: '2' },
    ],
  },
  {
    name: 'GoogleFontsSelector',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Interface Font',
    description: 'Select a font from the Google Fonts library or choose to use your system font.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Open Sans', value: '1' },
      { name: 'Roboto', value: '2' },
      { name: 'Roboto Condensed', value: '3' },
      { name: 'Droid Sans', value: '4' },
      { name: 'Inconsolata', value: '5' },
      { name: 'System font', value: '6' },
    ],
  },
  {
    name: 'HideAccountBalancesType',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Hide Account Balances',
    description: 'Allows you to hide account type totals and/or account balances.',
    options: [
      { name: 'Disabled', value: '0' },
      { name: 'Hide All', value: '1' },
      { name: 'Hide Account Type Totals', value: '2' },
      { name: 'Hide Account Balances', value: '3' },
    ],
  },
  {
    name: 'HideClosedAccounts',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Hide Closed Accounts',
    description:
      'This feature hides the closed accounts section in the side menu. View the account-options popup (click your e-mail) to show or hide the closed accounts.',
  },
  {
    name: 'HideHelp',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Hide Help (?) Button',
    description:
      'This feature hides the blue help (?) button in the bottom right corner of the screen. View the account-options popup (click your e-mail) to show or hide the help button.',
  },
  {
    name: 'HideReferralBanner',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Hide Referral Banner',
    description:
      'YNAB shows a "Share YNAB, Get YNAB free" banner. If you\'d rather not see this banner, you can turn this feature on to hide it.',
  },
  {
    name: 'ImportNotification',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Show Import Notifications in Navigation Sidebar',
    description:
      'Underline account names in the navigation sidebar that have transactions to be imported. Hovering the mouse over the account name will display the number of transactions to be imported.',
    options: [
      { name: 'Off', value: '0' },
      { name: 'On - Underline account names in white', value: '1' },
      { name: 'On - Underline account names in red', value: '2' },
    ],
  },
  {
    name: 'NavDisplayDensity',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Navigation Tabs Height',
    description:
      'Makes the navigation tabs (Budget, Reports, etc) smaller, and with less padding, so that you can see more of the sidebar on the screen.',
    options: [
      { name: 'Default', value: '0' },
      { name: 'Compact', value: '1' },
      { name: 'Slim', value: '2' },
    ],
  },
  {
    name: 'POSStyleCurrencyEntryMode',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'POS-style currency entry mode',
    description:
      'Allow entry of currency values without decimal separators (as done in real-life on POS terminals). For example, entering a figure of "500" will expand to "5.00". Values containing decimal separator of current account are left unmodified (e.g. "50.00" will stay "50.00"). As a shorthand, values ending with "-" will be expanded to full monetary unit (e.g. "50-" will result in "50.00"). Math operations are supported as well (e.g. "50*5" becomes "2.50").',
  },
  {
    name: 'PrintingImprovements',
    type: 'checkbox',
    default: true,
    section: 'general',
    title: 'Printing Improvements',
    description:
      'Changes print styles so budget and account sections can be easily printed. Due to the number of columns, the account section should be printed using landscape orientation.',
  },
  {
    name: 'PrivacyMode',
    type: 'select',
    default: '0',
    section: 'general',
    title: 'Privacy Mode',
    description:
      'Obscures dollar amounts everywhere until hovered. In toggle mode, a lock icon will appear in the lower left corner of YNAB. Click to enable or disable privacy mode.',
    options: [
      { name: 'Disabled', value: '0' },
      { name: 'Always On', value: '1' },
      { name: 'Add Toggle Button', value: '2' },
    ],
  },
  {
    name: 'SquareNegativeMode',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Square Negative Mode',
    description:
      'Changes the round borders on all negative numbers to square. Helps them become more of an eyesore so you want to get rid of them!',
  },
  {
    name: 'UnclearedAccountHighlight',
    type: 'checkbox',
    default: false,
    section: 'general',
    title: 'Uncleared Account Highlight',
    description:
      'Adds a small indicator next to account balances on the sidebar to indicate not all transactions are cleared.',
  },
  {
    name: 'CompactIncomeVsExpense',
    type: 'checkbox',
    default: false,
    section: 'reports',
    title: 'Compact Income vs. Expense',
    description:
      "Modifies styling of the Income vs. Expense report so it doesn't use too much white space on the page.",
  },
  {
    name: 'IncomeVsExpenseHoverHighlight',
    type: 'checkbox',
    default: true,
    section: 'reports',
    title: 'Highlight Income vs Expense Row on Hover',
    description:
      'Provides a highlight over the currently hovered row on the native YNAB Income vs Expense report.',
  },
  {
    name: 'ViewZeroAsEmpty',
    type: 'checkbox',
    default: false,
    section: 'reports',
    title: 'View Zero as Empty',
    description:
      'If a cell is zero, replace it with an empty cell so it is easier to focus on non-zero cells. "Total" rows are not modified.',
  },
  {
    name: 'HideDebtRatio',
    type: 'checkbox',
    default: false,
    section: 'toolkitReports',
    title: 'Hide Debt Ratio in Toolkit Reports: Net Worth',
    description: 'Hide debt ratio (debts / assets * 100%) in the Toolkit Reports Net Worth page',
  },
  {
    name: 'ToolkitReports',
    section: 'general',
    default: true,
    type: 'checkbox',
    title: 'Toolkit Reports',
    description:
      'Adds Toolkit Reports to the sidebar. Current reports include: Net Worth, Spending By Category/Payee, and Income vs Expense',
  },
];

// eslint-disable-next-line quotes, object-curly-spacing, quote-props
window.ynabToolKit.settings = allToolkitSettings;

// We don't update these from anywhere else, so go ahead and freeze / seal the object so nothing can be injected.
Object.freeze(window.ynabToolKit.settings);
Object.seal(window.ynabToolKit.settings);
