/*
 **********************************************************
 * Warning: This is a file generated by the build process. *
 *                                                         *
 * Any changes you make manually will be overwritten       *
 * the next time you run ./build or build.bat!             *
 ***********************************************************
 */

(function poll() {
  if (typeof ynabToolKit.shared !== 'undefined') {
    ynabToolKit.shared.feedChanges = function(changes) {
      try {
        if (changes.changedNodes) ynabToolKit.l10n.observe(changes.changedNodes);
      } catch (err) {
        /* ignore */
      }
    };
  } else if (typeof Ember !== 'undefined') {
    Ember.run.next(poll, 250);
  } else {
    setTimeout(poll, 250);
  }
})();
