/*
 **********************************************************
 * Warning: This is a file generated by the build process. *
 *                                                         *
 * Any changes you make manually will be overwritten       *
 * the next time you run ./build or build.bat!             *
 ***********************************************************
 */

(function poll() {
  if (typeof ynabToolKit.shared !== 'undefined') {
    ynabToolKit.shared.feedChanges = function (changes) {
      // Python script auto builds up this list of features
      // that will use the mutation observer from actOnChange()

      // If a feature doesn't need to use observe(), we
      // just let it fail silently

      try {
        if (changes.changedNodes) ynabToolKit.compactIncomeExpense.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.compactIncomeExpense.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.enlargeCategoriesDropdown.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.enlargeCategoriesDropdown.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.budgetPopupCalculator.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.budgetPopupCalculator.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.budgetProgressBars.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.budgetProgressBars.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.reports.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.reports.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.rightClickToEdit.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.rightClickToEdit.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.moveMoneyAutocomplete.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.moveMoneyAutocomplete.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.swapClearedFlagged.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.swapClearedFlagged.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.goalIndicator.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.goalIndicator.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.spendingByPayee.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.spendingByPayee.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.popupCalculator.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.popupCalculator.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.removeZeroCategories.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.removeZeroCategories.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.incomeVsExpense.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.incomeVsExpense.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.budgetCategoryInfo.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.budgetCategoryInfo.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.insertPacingColumns.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.insertPacingColumns.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.spareChange.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.spareChange.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.spendingByCategory.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.spendingByCategory.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.toggleTransactionFilters.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.toggleTransactionFilters.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.l10n.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.l10n.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.netWorthReport.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.netWorthReport.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.incomeFromLastMonth.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.incomeFromLastMonth.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.splitTransactionAutoAdjust.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.splitTransactionAutoAdjust.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }

      try {
        if (changes.changedNodes) ynabToolKit.accountPopupCalculator.observe(changes.changedNodes);
        if (changes.routeChanged) ynabToolKit.accountPopupCalculator.onRouteChanged(changes.routeChanged);
      } catch (err) { /* ignore */ }
    };
  } else {
    setTimeout(poll, 100);
  }
}());
