#!/usr/bin/env bash

if [ "$1" == "" ]; then
  echo "Please supply a Crowdin API key, obtained on this page: http://translate.toolkitforynab.com/project/toolkit-for-ynab/settings#api"
  exit 1
fi

echo "Downloading l10ns from Crowdin."
cd src/extension/legacy/features/l10n
python init.py $1
cd -
