module.exports = {
  name: 'SavingsRatio',
  type: 'select',
  default: '0.10',
  section: 'toolkitReports',
  title: 'Savings Ratio',
  description:
    'Display savings ratio (how much of income you do not spend) in Toolkit reports. Enable this to select target savings ratio. All values below this threshold will be painted red.',
  options: [
    { name: '5%', value: '0.05' },
    { name: '10%', value: '0.10' },
    { name: '15%', value: '0.15' },
    { name: '20%', value: '0.20' },
    { name: '25%', value: '0.25' },
    { name: '30%', value: '0.30' },
    { name: '35%', value: '0.35' },
    { name: '40%', value: '0.40' },
    { name: '45%', value: '0.45' },
    { name: '50%', value: '0.50' },
    { name: '55%', value: '0.55' },
    { name: '60%', value: '0.60' },
    { name: '65%', value: '0.65' },
    { name: '70%', value: '0.70' },
    { name: '75%', value: '0.75' },
    { name: '80%', value: '0.80' },
    { name: '85%', value: '0.85' },
    { name: '90%', value: '0.90' },
    { name: '95%', value: '0.95' },
  ],
};
