name: CI/CD Semantic Release

on:
  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - './scripts/**'
      - '.config/releaserc.js'
  workflow_dispatch: {}

env:
  HUSKY: 0

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          fetch-tags: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          AMO_JWT_KEY: ${{ secrets.AMO_JWT_KEY }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        run: npx semantic-release --debug

      - name: Merge main branch -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          github_token: ${{ secrets.GH_TOKEN }}
          from_branch: ${{ github.ref_name }}
          target_branch: develop
          message: 'chore(ci): sync develop with ${{ github.ref_name }} [skip ci]'
